/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.Visores;

import internal.BCliente;
import internal.BConnector;
import internal.BTrabajador;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import visual.VArriendos;

/**
 *
 * @author RemoteUser
 */
public class VClientes extends javax.swing.JFrame {

    /**
     * Creates new form VClientes
     */
    public VClientes() {
        initComponents();
        
        InitClientes();
    }
    
    public void InitClientes(){
        ArrayList<BCliente> clientes = BCliente.GetAllClientes();
        
        DefaultListModel model = new DefaultListModel();

        if(clientes.size() > 0){
            for (int i = 0; i < clientes.size(); i++) {
                model.addElement(clientes.get(i).getFullNameCode());
            }
        }
        clientsList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientsList = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        addClient = new javax.swing.JMenu();
        btnDelete = new javax.swing.JMenu();
        updateClient = new javax.swing.JMenu();
        btnUpdate = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes");

        clientsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(clientsList);

        addClient.setText("Nuevo");
        addClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addClientMouseClicked(evt);
            }
        });
        addClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientActionPerformed(evt);
            }
        });
        jMenuBar1.add(addClient);

        btnDelete.setText("Eliminar");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnDelete);

        updateClient.setText("Actualizar Cliente");
        updateClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateClientMouseClicked(evt);
            }
        });
        jMenuBar1.add(updateClient);

        btnUpdate.setText("Actualizar Lista");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnUpdate);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientActionPerformed
        VNewClient clientPage = new VNewClient();
        clientPage.pack();
        clientPage.setLocationRelativeTo(null); 
        clientPage.setVisible(true);
        this.setEnabled(true);
    }//GEN-LAST:event_addClientActionPerformed

    private void addClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClientMouseClicked
        VNewClient clientPage = new VNewClient();
        clientPage.pack();
        clientPage.setLocationRelativeTo(null); 
        clientPage.setVisible(true);
        this.setEnabled(true);
    }//GEN-LAST:event_addClientMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        String rut = JOptionPane.showInputDialog("Ingrese el Rut del cliente a eliminar");
        if(rut != null && !rut.equals("")){
            ResultSet clientid = BConnector.ExecuteQueryResult("SELECT id FROM Cliente WHERE rut = '" + rut + "';");
            
            try{
                if(clientid.next()){
                    ArrayList<String> deleteQueries = new ArrayList();
                    
                    int id = clientid.getInt("id");
                    
                    deleteQueries.add("DELETE FROM Cliente_Correo WHERE cliente_id = " + id + ";");
                    deleteQueries.add("DELETE FROM Cliente_Direccion WHERE cliente_id = " + id + ";");
                    deleteQueries.add("DELETE FROM Cliente_Telefono WHERE cliente_id = " + id + ";");
                    
                    deleteQueries.add("DELETE FROM Cliente WHERE rut = '" + rut + "';");
                    
                    if(BConnector.ExecuteBatch(deleteQueries)){
                        JOptionPane.showMessageDialog(null, "Cliente eliminado");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se ha encontrado un cliente con ese Rut");
                    btnDeleteMouseClicked(evt);
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
            }
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        InitClientes();
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void updateClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateClientMouseClicked
        String rut = JOptionPane.showInputDialog("Ingrese el Rut para Actualizar");
        
        if(rut != null && !rut.equals("")){
            ResultSet result = BConnector.ExecuteQueryResult("SELECT id FROM Cliente WHERE rut = '"+rut+"'");
            
            try{
                if(result.next()){
                    VNewClient clientPage = new VNewClient(rut);
                    clientPage.pack();
                    clientPage.setLocationRelativeTo(null); 
                    clientPage.setVisible(true);
                    this.setEnabled(true);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Rut no encontrado");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
            }
        }
    }//GEN-LAST:event_updateClientMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu addClient;
    private javax.swing.JMenu btnDelete;
    private javax.swing.JMenu btnUpdate;
    private javax.swing.JList<String> clientsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu updateClient;
    // End of variables declaration//GEN-END:variables
}
