/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.Visores;

import internal.BCliente;
import internal.BUtilities;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author RemoteUser
 */
public class VNewClient extends javax.swing.JFrame {

    /**
     * Creates new form VNewClient
     */
    public VNewClient() {//Adaptar a trabajador
        initComponents();
        
        InitLists();
    }
    
    BCliente clientRef = null;
    
    public VNewClient(String rut){
        initComponents();
        
        clientRef = BCliente.GetClienteByRut(rut);
        titleLabel.setText("Cliente: " + clientRef.getFullNameCode());
        
        rutLabel.setText(clientRef.getRut());
        rutLabel.setEnabled(false);
        
        nombreLabel.setText(clientRef.getNombre());
        apellidoPaternoLabel.setText(clientRef.getApellidoPaterno());
        apellidoMaternoLabel.setText(clientRef.getApellidoMaterno());
        
        dayLabel.setSelectedItem(BUtilities.getDayFromDate(clientRef.getFecha()));
        monthLabel.setSelectedItem(BUtilities.getMonthFromDate(clientRef.getFecha()));
        yearLabel.setSelectedItem(BUtilities.getYearFromDate(clientRef.getFecha()));
        
        btnConfirm.setText("Actualizar");
        
        InitLists();
    }
    
    DefaultListModel correoModel = new DefaultListModel();
    DefaultListModel telefonoModel = new DefaultListModel();
    DefaultListModel direccionModel = new DefaultListModel();
    
    ArrayList<String> newCorreos = new ArrayList();
    ArrayList<String> newTelefonos = new ArrayList();
    ArrayList<String> newDirecciones = new ArrayList();
    
    private void InitLists(){     
        if(clientRef != null){
            for (int i = 0; i < clientRef.getCorreos().size(); i++) {
                correoModel.addElement(clientRef.getCorreos().get(i));
            }
            for (int i = 0; i < clientRef.getTelefonos().size(); i++) {
                telefonoModel.addElement(clientRef.getTelefonos().get(i));
            }
            for (int i = 0; i < clientRef.getDirecciones().size(); i++) {
                direccionModel.addElement(clientRef.getDirecciones().get(i));
            }
        }
        
        UpdateModels();
    }
    
    private void UpdateModels(){
        correosList.setModel(correoModel);
        telefonosList.setModel(telefonoModel);
        direccionesList.setModel(direccionModel);
    }
    
    private void AddElementToModel(DefaultListModel modelRef, String value){
        modelRef.addElement(value);
        
        UpdateModels();
    }//Adaptar a trabajador

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        rutLabel = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        apellidoPaternoLabel = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        apellidoMaternoLabel = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        dayLabel = new javax.swing.JComboBox<>();
        monthLabel = new javax.swing.JComboBox<>();
        yearLabel = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        telefonosList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        correosList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        direccionesList = new javax.swing.JList<>();
        btnConfirm = new javax.swing.JButton();
        newCorreo = new javax.swing.JButton();
        newDireccion = new javax.swing.JButton();
        newTelefono = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Cliente");

        titleLabel.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Añadir Cliente");

        rutLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rutLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rutLabel.setToolTipText("Ingrese Rut sin puntos ni guión");

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Rut");

        nombreLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        nombreLabel.setToolTipText("Ingrese Nombre");

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Nombre");

        jLabel18.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Apellido Paterno");

        apellidoPaternoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        apellidoPaternoLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        apellidoPaternoLabel.setToolTipText("Ingrese Apellido Paterno");

        jLabel19.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Apellido Materno");

        apellidoMaternoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        apellidoMaternoLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        apellidoMaternoLabel.setToolTipText("Ingrese Apellido Materno");

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Correos");

        dayLabel.setEditable(true);
        dayLabel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        monthLabel.setEditable(true);
        monthLabel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        yearLabel.setEditable(true);
        yearLabel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));

        jLabel21.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Fecha de Nacimiento");

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Teléfonos");

        jLabel23.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Direcciones");

        telefonosList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(telefonosList);

        correosList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        correosList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                correosListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(correosList);

        direccionesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(direccionesList);

        btnConfirm.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        btnConfirm.setText("Añadir Cliente");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        newCorreo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        newCorreo.setText("Nuevo Correo");
        newCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCorreoActionPerformed(evt);
            }
        });

        newDireccion.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        newDireccion.setText("Nueva Direccion");
        newDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDireccionActionPerformed(evt);
            }
        });

        newTelefono.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        newTelefono.setText("Nuevo Telefono");
        newTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirm)
                        .addGap(264, 264, 264))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(monthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yearLabel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidoPaternoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidoMaternoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(newDireccion)))
                                    .addComponent(newCorreo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newTelefono))))
                        .addGap(30, 30, 30))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(475, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rutLabel)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoPaternoLabel)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoMaternoLabel)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(306, 306, 306)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(370, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        boolean incomplete = false;
        if(rutLabel.getText().equals("")){
            incomplete = true;
        }
        if(nombreLabel.getText().equals("")){
            incomplete = true;
        }
        if(apellidoPaternoLabel.getText().equals("")){
            incomplete = true;
        }
        if(apellidoMaternoLabel.getText().equals("")){
            incomplete = true;
        }
        if(((String)dayLabel.getSelectedItem()).equals("")){
            incomplete = true;
        }
        if(((String)monthLabel.getSelectedItem()).equals("")){
            incomplete = true;
        }
        if(((String)yearLabel.getSelectedItem()).equals("")){
            incomplete = true;
        }
        
        if(correoModel.getSize() <= 0 || telefonoModel.getSize() <= 0 || direccionModel.getSize() <= 0){
            incomplete = true;
        }
        
        String fecha = BUtilities.DateFormatString((String)dayLabel.getSelectedItem(), (String)monthLabel.getSelectedItem(), (String)yearLabel.getSelectedItem());
        
        if(incomplete){
            JOptionPane.showMessageDialog(null, "Datos incompletos");
            return;
        }//validacion
        
        if(clientRef != null){
            if(BCliente.AddClient(rutLabel.getText(), nombreLabel.getText(), apellidoPaternoLabel.getText(), apellidoMaternoLabel.getText(), 
                    fecha, newCorreos, newTelefonos, newDirecciones, false, Integer.toString(clientRef.getId()))){
                JOptionPane.showMessageDialog(null, "Cliente actualizado");
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Se ha producido un error");
                return; 
            }
        }// aqui
        else{
            if(BCliente.AddClient(rutLabel.getText(), nombreLabel.getText(), apellidoPaternoLabel.getText(), apellidoMaternoLabel.getText(), 
                    fecha, BUtilities.ModelOfStringsToArrayList(correoModel), BUtilities.ModelOfStringsToArrayList(telefonoModel), BUtilities.ModelOfStringsToArrayList(direccionModel), true, null)){
                JOptionPane.showMessageDialog(null, "Cliente añadido");
                rutLabel.setText("");
                nombreLabel.setText("");
                apellidoPaternoLabel.setText("");
                apellidoMaternoLabel.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null, "Se ha producido un error");
                return; 
            }//aqui
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void correosListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_correosListValueChanged

    }//GEN-LAST:event_correosListValueChanged

    private void newCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCorreoActionPerformed
        String correo = JOptionPane.showInputDialog("Ingrese un Correo");
        
        if(correo != null && !correo.equals("")){
            if(clientRef != null){
                newCorreos.add(correo);
            }
            AddElementToModel(correoModel, correo);
        }
    }//GEN-LAST:event_newCorreoActionPerformed

    private void newDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDireccionActionPerformed
        String direccion = JOptionPane.showInputDialog("Ingrese una Dirección");
        
        if(direccion != null && !direccion.equals("")){
            if(clientRef != null){
                newDirecciones.add(direccion);
            }
            AddElementToModel(direccionModel, direccion);
        }
    }//GEN-LAST:event_newDireccionActionPerformed

    private void newTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTelefonoActionPerformed
        String telefono = JOptionPane.showInputDialog("Ingrese un Telefono");
        
        if(telefono != null && !telefono.equals("")){
            if(clientRef != null){
                newTelefonos.add(telefono);
            }
            AddElementToModel(telefonoModel, telefono);
        }
    }//GEN-LAST:event_newTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VNewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VNewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VNewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VNewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VNewClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoMaternoLabel;
    private javax.swing.JTextField apellidoPaternoLabel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JList<String> correosList;
    private javax.swing.JComboBox<String> dayLabel;
    private javax.swing.JList<String> direccionesList;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> monthLabel;
    private javax.swing.JButton newCorreo;
    private javax.swing.JButton newDireccion;
    private javax.swing.JButton newTelefono;
    private javax.swing.JTextField nombreLabel;
    private javax.swing.JTextField rutLabel;
    private javax.swing.JList<String> telefonosList;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> yearLabel;
    // End of variables declaration//GEN-END:variables
}
